CREATE TABLE usuarios (id SERIAL PRIMARY KEY, usuario VARCHAR(80) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL);
CREATE TABLE proveedores (id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, contacto VARCHAR(80) NOT NULL, ciudad VARCHAR(60) NOT NULL, calificacion INTEGER NOT NULL);
CREATE TABLE clientes (id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, email VARCHAR(120) UNIQUE NOT NULL, telefono VARCHAR(20) NOT NULL, activo BOOLEAN DEFAULT TRUE);
CREATE TABLE productos (id SERIAL PRIMARY KEY, nombre VARCHAR(80) NOT NULL, categoria VARCHAR(60) NOT NULL, precio NUMERIC(10,2) NOT NULL, stock INTEGER NOT NULL, proveedor_id INTEGER REFERENCES proveedores(id));
CREATE TABLE facturas (id SERIAL PRIMARY KEY, numero VARCHAR(20) UNIQUE NOT NULL, cliente_id INTEGER NOT NULL REFERENCES clientes(id), total NUMERIC(10,2) NOT NULL, estado VARCHAR(20) NOT NULL);
